Repository oncodash/ontoweaver, pull requests merged in 2024-12, with the labels that each got.

#64 feat(readme):Example for replace transformer.
  README.md
Labels: documentation

#71 refactor: error management
  src/ontoweaver/base.py
  src/ontoweaver/tabular.py
Labels: bug, enhancement, refactoring

#65 Feat: CLI "ontoweave"
  README.md
  pyproject.toml
  src/ontoweaver/__init__.py
  src/ontoweaver/exceptions.py
  src/tools/ontoweave
  src/tools/ontoweave.py
  tests/test_ontoweave.py
Labels: enhancement

#74 Fix ci pipeline. Update to Python 3.13.
  .github/workflows/ci.yaml
  pyproject.toml
Labels: bug

#76 Fix CI pipeline and add exceptions module to __init__.
  .github/workflows/ci.yaml
  src/ontoweaver/__init__.py
Labels: bug

#79 fix(from_subject):Error if declared == default.
  src/ontoweaver/tabular.py
Labels: bug
