Repository oncodash/ontoweaver, pull requests merged in 2024-10, with the labels that each got.

#30 fix rowIndex & map and clean logging
  src/ontoweaver/base.py
  src/ontoweaver/tabular.py
  src/ontoweaver/transformer.py
Labels: bug, enhancement

#34 refactor(preprocess): makes CLI more POSIX
  src/preprocessing/preprocess_ontology.py
  src/tools/preprocess_ontology.py
Labels: documentation, enhancement

#33 Metadata for nodes and edges
  README.md
  pyproject.toml
  src/ontoweaver/tabular.py
  src/ontoweaver/transformer.py
Labels: enhancement
