Repository oncodash/ontoweaver, pull requests merged in 2025-05, with the labels that each got.

#143 Output validation fixes.
  src/ontoweaver/__init__.py
  src/ontoweaver/base.py
  src/ontoweaver/ontoweave.py
  src/ontoweaver/tabular.py
  src/ontoweaver/transformer.py
  src/ontoweaver/validate.py
  tests/test_2_databases.py
  tests/test_oncokb.py
  tests/test_output_validation.py
  tests/test_parallel_mapping.py
Labels: enhancement, feature

#146 Doc readme
  README.md
  docs/OntoWeaver__simple-summary.svg
Labels: documentation

#153 Enable usage of `rowIndex` for target nodes. Fix errors with `final_type`.
  src/ontoweaver/make_labels.py
  src/ontoweaver/tabular.py
  tests/final_type/mapping.yaml
  tests/test_final_type.py
Labels: bug, enhancement
